### ISSUE TITLE
Support for parsing StreamCharts/SullyGnome/TwitchTracker links

### ISSUE THREAD

**Issue by Infinitay** [ItIckeYd/VodRecovery#41]
- SullyGnome
	- They seem to have an API, but they use another form of ID in their calls.
		- https://sullygnome.com/api/tables/channeltables/streams/7/194103/%20/1/1/desc/0/10
			- Not sure what the ID of `194103` signifies or where it is from, but I would have thought for them to use the streamer's user id which is not `194103` in this case

- StreamCharts
	- Since they use CloudFlare and removed their public API, it's hard to fetch the data required. There is a Python package https://github.com/VeNoMouS/cloudscraper available, but I don't believe it's working at the moment as CF changed their challenge. YMMV? Of course this would mean that whenever CloudFlare changes our support for parsing StreamCharts data would potentionally break.
	- Another way would be to use an automation library/framework such as puppeteer and use a headless browser to access the page and get the data required. This works with https://github.com/microsoft/playwright-python but packaging a browser seems too much.
		- You could make it it will use the user's own browser, but I think only Chrome is supported for that at this time.

- TwitchTracker
	- Currently this seems the most viable. There is no public API, but there also isn't CloudFlare or anything else that would stop VocRecovery from making a request and getting the data required. `.stream-timestamp-dt` and you should be good to go after parsing it to the required format. 
	- I had a concern about the site slowing down more than it already is, but I don't think there are lots of people using VodRecovery to begin with. Additionally, it's just one request.

**Comment by ItIckeYd** [comment]
@Infinitay thank you for the suggestions. I understand that parsing of those sites would be great for the script however that comes with a lot of extra work trying to figure out how exactly to parse it using beautifulsoup and possibly a public api if it existed. 

The scraping of sites brings an unneeded level of maintenance to the script due to if any of the sites changed any part of their UI.

I think the way the script works now is perfect in the fact that it depends on the user input alone and doesn't rely on outside factors like 

- developers of site changing UI
- possible changes in the url format
- API moving from public to paid like streamscharts.

Those are the main reasons I will most likely not be implementing this into the script. The main goal of the script was to provide something stable and useable.. and I think this script achieves both of those things by being user dependent and not dependent on outside factors that are not in my control.

**Comment by Infinitay** [comment]
Understood, thanks for the reasoning on not wanting to do so
