### ISSUE TITLE
Could not get bulk recover to work

### ISSUE THREAD

**Issue by meptike** [ItIckeYd/VodRecovery#65]
Hi,

I open die .csv in excel but I do not get any prompt regarding saving again.
How does the .csv has to be?

Thx

**Comment by ItIckeYd** [comment]
@meptike you just need to download the CSV.. then open it and save it.

**Comment by meptike** [comment]
Does not work for me
![image](https://user-images.githubusercontent.com/43492194/181184493-d09e6c89-ffc6-4d7e-889b-533663698d20.png)

**Comment by ItIckeYd** [comment]
@meptike So what did you do so far? 

Obviously you downloaded the csv from sullygnome. Did you open it in excel and save it? Also when saving it did you get a prompt stating "Some features in your workbook might be lost if you save it as CSV. Do you want to keep using that format"  If so did you click "yes".

The error that you gave is usually due to not saving the CSV after downloading it... I have never gotten that error once I saved the CSV after downloading as saving it ensures formatting of the CSV.

**Comment by meptike** [comment]
Yes, I open the csv in Excel (via doubleclick) and save it again, but do not get any "keep using that format..."

**Comment by ItIckeYd** [comment]
@meptike Please provide sullygnome link where csv file was downloaded? Will help me troubleshoot.

**Comment by meptike** [comment]
From this site: https://sullygnome.com/channel/elizabethqueenn/2021may/streams

Thx for the support!

**Comment by ItIckeYd** [comment]
@meptike Worked for me.. Maybe try "saving as".... honestly i'm not quite sure how to fix it.

**Comment by benlanben** [comment]
I don't have excel, I use this site: https://www.convertcsv.com/csv-viewer-editor.htm to open the sullygnome csv files and download the opened files to use with the program.

**Comment by blackesteagle** [comment]
I don't have excel, I use this site: https://www.convertcsv.com/csv-viewer-editor.htm to open the sullygnome csv files and download the opened files to use with the program.

**Comment by meptike** [comment]
works perfect with convertcsv.com, with my excel365 it does not work. thx!

**Comment by ItIckeYd** [comment]
@meptike @blackesteagle This issue is now fixed.

It is no longer required to save the CSV after downloading from sullygnome. The script will work without any manual intervention after downloading.
