### ISSUE TITLE
Download m3u8

### ISSUE THREAD

**Issue by hokkino** [ItIckeYd/VodRecovery#83]
Is there any method to download the m3u8 from a exactly time?
The stream vod (m3u8) link has 12 hours of video, but I just want to download until the 5 hours of stream, to get to watch it quicker. Is that possible some how?

If not, Im asking you to please a feauture that you can select the exactly time that you want to download, the begin and end of it. This would be awesome.

Ty for the job!

**Comment by ItIckeYd** [comment]
Just through researching this for a couple minutes....  I have a feeling this would require a substantial refactor of the script in order to implement correctly.... which would in turn take a considerable amount of time and effort.

For that reason I am going to mark this as a feature that will not be implemented into the script.

I appreciate the suggestion and support for the script but the feature in question is just out of scope for what I am willing to develop.
